#!/usr/bin/env python3

from helpers import get_user_timeline
import sys
import os
from termcolor import colored
from analyzer import Analyzer

def main():
    if len(sys.argv)!=2:
        sys.exit("Usage: ./tweets @screen name")
        
    positives = os.path.join(sys.path[0],"positive-words.txt")
    negatives = os.path.join(sys.path[0],"negative-words.txt")
    analyzer = Analyzer(positives, negatives)
    
    tweets = get_user_timeline(sys.argv[1].strip("@"), 50)
    
    if tweets == None:
        sys.exit("User is private or doesn't exist.")
    
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}".format(score, tweet),"green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet),"red"))
        else:
            print(colored("{} {}".format(score, tweet),"yellow"))

if __name__ == "__main__":
    main()